<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WechatDashboard.Application\WechatDashboard.Application.csproj" />
    <ProjectReference Include="..\WechatDashboard.Domain\WechatDashboard.Domain.csproj" />
    <ProjectReference Include="..\WechatDashboard.Infrastructure\WechatDashboard.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
